export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_FEATURED_POSTS = 'FETCH_FEATURED_POSTS';
export const FETCH_FEATURED_POSTS_SUCCESS = 'FETCH_FEATURED_POSTS_SUCCESS';
export const FETCH_FEATURED_POSTS_FAILURE = 'FETCH_FEATURED_POSTS_FAILURE';
export const FETCH_DRAFT_POSTS = 'FETCH_DRAFT_POSTS';
export const FETCH_DRAFT_POSTS_SUCCESS = 'FETCH_DRAFT_POSTS_SUCCESS';
export const FETCH_DRAFT_POSTS_FAILURE = 'FETCH_DRAFT_POSTS_FAILURE';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
export const FETCH_CONTENT = 'FETCH_CONTENT';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const ADMIN = 'ADMIN';

export const OPEN_ALERT_DIALOG = 'OPEN_ALERT_DIALOG';
export const CLOSE_ALERT_DIALOG = 'CLOSE_ALERT_DIALOG';

export const OPEN_BLOG_DIALOG = 'OPEN_BLOG_DIALOG';
export const CLOSE_BLOG_DIALOG = 'CLOSE_BLOG_DIALOG';

export const FETCH_THEME = 'FETCH_THEME';
export const FETCH_THEME_SUCCESS = 'FETCH_THEME_SUCCESS';
export const FETCH_THEME_FAILURE = 'FETCH_THEME_FAILURE';

export const OPEN_ADMIN_DRAWER = 'OPEN_ADMIN_DRAWER';
export const CLOSE_ADMIN_DRAWER = 'CLOSE_ADMIN_DRAWER';
export const UPDATE_PATHNAME = 'UPDATE_PATHNAME';

export const FETCH_YOUTUBE_CHANNEL = 'FETCH_YOUTUBE_CHANNEL';
export const FETCH_YOUTUBE_CHANNEL_SUCCESS = 'FETCH_YOUTUBE_CHANNEL_SUCCESS';
export const FETCH_YOUTUBE_CHANNEL_FAILURE  = 'FETCH_YOUTUBE_CHANNEL_FAILURE';

export const FETCH_YOUTUBE_UPLOADS = 'FETCH_YOUTUBE_UPLOADS';
export const FETCH_YOUTUBE_UPLOADS_SUCCESS = 'FETCH_YOUTUBE_UPLOADS_SUCCESS';
export const FETCH_YOUTUBE_UPLOADS_FAILURE  = 'FETCH_YOUTUBE_UPLOADS_FAILURE';
export const PLAY_VIDEO = 'PLAY_VIDEO';
export const CLOSE_VIDEO = 'CLOSE_VIDEO';